#           Flight Price Prediction-Scraping

You have to scrape at least 1500 rows of data. You can scrape more data as well, it’s up to you, 
More the data better the model
In this section you have to scrape the data of flights from different websites (yatra.com, 
skyscanner.com, official websites of airlines, etc). The number of columns for data doesn’t have 
limit, it’s up to you and your creativity. Generally, these columns areairline name, date of journey, 
source, destination, route, departure time, arrival time, duration, total stops and the target variable 
price. You can make changes to it, you can add or you can remove some columns, it completely
depends on the website from which you are fetching the data.

In [1]:
# Importing Libraries
import pandas as pd
import selenium
from selenium import webdriver
import time
from selenium.common.exceptions import StaleElementReferenceException, NoSuchElementException
from selenium.webdriver.support import expected_conditions as EC
import time
from selenium.webdriver.support.ui import WebDriverWait
from selenium.webdriver.common.by import By
from selenium.webdriver.common.keys import Keys

In [2]:
# path for chromedriver
options = webdriver.ChromeOptions() 
options.add_argument("start-maximized")
driver=webdriver.Chrome("chromedriver.exe")
time.sleep(10)

In [4]:
# enter keyword to search (URL)
#keyword="https://flight.yatra.com/air-search-ui/dom2/trigger?ADT=1&CHD=0&INF=0&class=Economy&destination=BOM&destinationCountry=IN&flexi=0&flight_depart_date=27%2F01%2F2022&hb=0&noOfSegments=1&origin=IXJ&originCountry=IN&type=O&unique=1593678528500&viewName=normal"
keyword="https://flight.yatra.com/air-search-ui/dom2/trigger?type=O&viewName=normal&flexi=0&noOfSegments=1&origin=DEL&originCountry=IN&destination=BOM&destinationCountry=IN&flight_depart_date=27%2F01%2F2022&ADT=1&CHD=0&INF=0&class=Economy&source=fresco-home&unqvaldesktop=729384782632"
driver.get(keyword)
time.sleep(35)
time.sleep(4)
# checking current window title
print('Current page: ',driver.title)

Current page:  Yatra.com | Delhi to Mumbai flights

In [5]:
# Activating webdriver
for _ in range(5000):
    driver.execute_script("window.scrollBy(0,7000)")
time.sleep(10)

In [6]:
# enter keyword to search (URL)
keyword="https://flight.yatra.com/air-search-ui/dom2/trigger?ADT=1&CHD=0&INF=0&class=Economy&destination=BOM&destinationCountry=IN&flexi=0&flight_depart_date=27%2F01%2F2022&hb=0&noOfSegments=1&origin=IXJ&originCountry=IN&type=O&unique=1593678528500&viewName=normal"
driver.get(keyword)
time.sleep(35)
time.sleep(4)
# checking current window title
print('Current page: ',driver.title)




# Activating webdriver
for _ in range(5000):
    driver.execute_script("window.scrollBy(0,7000)")
time.sleep(10)


airline_name=[]
date_of_journey=[]
source=[]
destination=[]
departure_time=[] 
arrival_time=[]
duration=[]
total_stops=[] 
price=[]

counter = 1
#data = []
while (counter <=1000):
    an=driver.find_elements_by_xpath('//div[@class="fs-13 airline-name no-pad col-8"]')  
    for i in an:
        try:
            airline_name.append(i.text)
        except NoSuchElementException:
            airline_name.append('-')
        
        
    s = driver.find_elements_by_xpath('//div[@class="i-b col-4 no-wrap text-right dtime col-3"]/p')  
    for i in s:
        try:
            source.append(i.text)
        except NoSuchElementException:
            source.append('-')
        
        
    d = driver.find_elements_by_xpath("//div[@class='i-b pdd-0 text-left atime col-5']/p[2]")  
    for i in d:
        try:
            destination.append(i.text)
        except NoSuchElementException:
            destination.append('-')
        
        
    de = driver.find_elements_by_xpath("//div[@class='i-b col-4 no-wrap text-right dtime col-3']/div")  
    for i in de:
        try:
            departure_time.append(i.text)
        except NoSuchElementException:
            departure_time.append('-')
        
        
    a = driver.find_elements_by_xpath("//div[@class='i-b pdd-0 text-left atime col-5']/p[1]") 
    for i in a:
        try:
            arrival_time.append(i.text)
        except NoSuchElementException:
            arrival_time.append('-')
        
        
    du = driver.find_elements_by_xpath('//div[@class="stop-cont pl-13"]/p')
    for i in du:
        try:
            duration.append(i.text)
        except NoSuchElementException:
            duration.append('-')
        
        
        
    ts = driver.find_elements_by_xpath('//span[@class="dotted-borderbtm"]')
    for i in ts:
        try:
              
            total_stops.append(i.text)
        except NoSuchElementException:
            total_stops.append('-')
        

    p = driver.find_elements_by_xpath('//div[@class="i-b tipsy fare-summary-tooltip fs-18"]')
    for i in p:
        try:
              
            price.append(i.text)
        except NoSuchElementException:
            price.append('-')
        
        if (counter>1100):
            break
        else:
            counter += 1
    time.sleep(2)
print("Done Scraping!!!")

Current page:  Yatra.com | Jammu to Mumbai flights
Done Scraping!!!

In [7]:
airline_data=pd.DataFrame({"Airline":airline_name})
source_data=pd.DataFrame({"Source":source})
destination_data=pd.DataFrame({"Destination":destination})
departure_time_data=pd.DataFrame({"Dep_Time":departure_time})
arrival_time_data=pd.DataFrame({"Arrival_Time":arrival_time})
duration_data=pd.DataFrame({"Duration":duration})
total_stops_data=pd.DataFrame({"Total_Stops":total_stops})
price_data=pd.DataFrame({"price":price})

data1=pd.concat([airline_data,source_data,destination_data,departure_time_data,arrival_time_data,duration_data,total_stops_data
          ,price_data],axis=1)
data1

,Airline,Source,Destination,Dep_Time,Arrival_Time,Duration,Total_Stops,price
0,IndiGo\n6E-137/2046,Jammu,Mumbai,11:55,19:25,7h 30m,2 Stop(s),"7,365"
1,IndiGo\n6E-137/5041,Jammu,Mumbai,11:55,20:50,8h 55m,2 Stop(s),"7,365"
2,IndiGo\n6E-609/6722,Jammu,Mumbai,14:00,23:30,9h 30m,2 Stop(s),"7,365"
3,IndiGo\n6E-137/6722,Jammu,Mumbai,11:55,23:30,11h 35m,2 Stop(s),"7,365"
4,SpiceJet\nSG-160/945,Jammu,Mumbai,11:15,16:15,5h 00m,1 Stop,"7,418"
...,...,...,...,...,...,...,...,...
1010,Air India\nAI-822/805,Jammu,Mumbai,15:45,22:10,6h 25m,1 Stop,"9,215"
1011,Air India\nAI-822/887,Jammu,Mumbai,15:45,09:05\n+ 1 day,17h 20m,1 Stop,"9,215"
1012,Air India\nAI-822/665,Jammu,Mumbai,15:45,10:10\n+ 1 day,18h 25m,1 Stop,"9,215"
1013,Air India\nAI-822/678,Jammu,Mumbai,15:45,11:15\n+ 1 day,19h 30m,1 Stop,"9,215"
1014,Air India\nAI-822/636,Jammu,Mumbai,15:45,18:00\n+ 1 day,26h 15m,2 Stop(s),"9,215"

In [8]:
# enter keyword to search (URL)
keyword="https://flight.yatra.com/air-search-ui/dom2/trigger?ADT=1&CHD=0&INF=0&class=Economy&destination=IXB&destinationCountry=IN&flexi=0&flight_depart_date=27%2F01%2F2022&hb=0&noOfSegments=1&origin=BOM&originCountry=IN&type=O&unique=1342525040225&version=1.1&viewName=normal"
driver.get(keyword)
time.sleep(35)
time.sleep(4)
# checking current window title
print('Current page: ',driver.title)




# Activating webdriver
for _ in range(5000):
    driver.execute_script("window.scrollBy(0,7000)")
time.sleep(10)


airline_name=[]
date_of_journey=[]
source=[]
destination=[]
departure_time=[] 
arrival_time=[]
duration=[]
total_stops=[] 
price=[]

counter = 1
#data = []
while (counter <=1000):
    an=driver.find_elements_by_xpath('//div[@class="fs-13 airline-name no-pad col-8"]')  
    for i in an:
        try:
            airline_name.append(i.text)
        except NoSuchElementException:
            airline_name.append('-')
        
        
    s = driver.find_elements_by_xpath('//div[@class="i-b col-4 no-wrap text-right dtime col-3"]/p')  
    for i in s:
        try:
            source.append(i.text)
        except NoSuchElementException:
            source.append('-')
        
        
    d = driver.find_elements_by_xpath("//div[@class='i-b pdd-0 text-left atime col-5']/p[2]")  
    for i in d:
        try:
            destination.append(i.text)
        except NoSuchElementException:
            destination.append('-')
        
        
    de = driver.find_elements_by_xpath("//div[@class='i-b col-4 no-wrap text-right dtime col-3']/div")  
    for i in de:
        try:
            departure_time.append(i.text)
        except NoSuchElementException:
            departure_time.append('-')
        
        
    a = driver.find_elements_by_xpath("//div[@class='i-b pdd-0 text-left atime col-5']/p[1]") 
    for i in a:
        try:
            arrival_time.append(i.text)
        except NoSuchElementException:
            arrival_time.append('-')
        
        
    du = driver.find_elements_by_xpath('//div[@class="stop-cont pl-13"]/p')
    for i in du:
        try:
            duration.append(i.text)
        except NoSuchElementException:
            duration.append('-')
        
        
        
    ts = driver.find_elements_by_xpath('//span[@class="dotted-borderbtm"]')
    for i in ts:
        try:
              
            total_stops.append(i.text)
        except NoSuchElementException:
            total_stops.append('-')
        

    p = driver.find_elements_by_xpath('//div[@class="i-b tipsy fare-summary-tooltip fs-18"]')
    for i in p:
        try:
              
            price.append(i.text)
        except NoSuchElementException:
            price.append('-')
        
        if (counter>1100):
            break
        else:
            counter += 1
    time.sleep(2)
print("Done Scraping!!!")

Current page:  Yatra.com | Mumbai to Bagdogra flights
Done Scraping!!!

In [9]:
airline_data=pd.DataFrame({"Airline":airline_name})
source_data=pd.DataFrame({"Source":source})
destination_data=pd.DataFrame({"Destination":destination})
departure_time_data=pd.DataFrame({"Dep_Time":departure_time})
arrival_time_data=pd.DataFrame({"Arrival_Time":arrival_time})
duration_data=pd.DataFrame({"Duration":duration})
total_stops_data=pd.DataFrame({"Total_Stops":total_stops})
price_data=pd.DataFrame({"price":price})

In [10]:
data2=pd.concat([airline_data,source_data,destination_data,departure_time_data,arrival_time_data,duration_data,total_stops_data
          ,price_data],axis=1)
data2

,Airline,Source,Destination,Dep_Time,Arrival_Time,Duration,Total_Stops,price
0,IndiGo\n6E-5209/149,Mumbai,Bagdogra,06:15,12:20,6h 05m,1 Stop,"8,528"
1,SpiceJet\nSG-163,Mumbai,Bagdogra,06:15,10:40,4h 25m,1 Stop,"8,678"
2,SpiceJet\nSG-8158/8903,Mumbai,Bagdogra,19:25,11:40\n+ 1 day,16h 15m,1 Stop,"8,678"
3,SpiceJet\nSG-8158/8493,Mumbai,Bagdogra,19:25,14:55\n+ 1 day,19h 30m,1 Stop,"8,678"
4,SpiceJet\nSG-8158/8187,Mumbai,Bagdogra,19:25,15:20\n+ 1 day,19h 55m,1 Stop,"8,678"
...,...,...,...,...,...,...,...,...
1010,Air India\nAI-570/766/721,Mumbai,Bagdogra,05:20,15:05\n+ 1 day,33h 45m,2 Stop(s),"13,878"
1011,Air India\nAI-619/559/879,Mumbai,Bagdogra,20:15,13:15\n+ 1 day,17h 00m,2 Stop(s),"14,678"
1012,Air India\nAI-867/401/721,Mumbai,Bagdogra,21:30,15:05\n+ 1 day,17h 35m,2 Stop(s),"14,678"
1013,Air India\nAI-888/401/721,Mumbai,Bagdogra,19:00,15:05\n+ 1 day,20h 05m,2 Stop(s),"14,678"
1014,Air India\nAI-660/401/721,Mumbai,Bagdogra,18:00,15:05\n+ 1 day,21h 05m,2 Stop(s),"14,678"

data1.to_csv('Web_Scraped_Flight_Data1.csv')

In [12]:
# enter keyword to search (URL)
keyword="https://flight.yatra.com/air-search-ui/dom2/trigger?ADT=1&CHD=0&INF=0&class=Economy&destination=GOI&destinationCountry=IN&flexi=0&flight_depart_date=27%2F01%2F2022&hb=0&noOfSegments=1&origin=BLR&originCountry=IN&type=O&unique=607742350031&version=1.1&viewName=normal"
driver.get(keyword)
time.sleep(35)
# checking current window title
print('Current page: ',driver.title)

Current page:  Challenge Validation

In [13]:
# Activating webdriver
for _ in range(5000):
    driver.execute_script("window.scrollBy(0,7000)")
time.sleep(10)

In [14]:
airline_name=[]
date_of_journey=[]
source=[]
destination=[]
departure_time=[] 
arrival_time=[]
duration=[]
total_stops=[] 
price=[]

counter = 1
#data = []
while (counter <=3000):
    an=driver.find_elements_by_xpath('//div[@class="fs-13 airline-name no-pad col-8"]')  
    for i in an:
        try:
            airline_name.append(i.text)
        except NoSuchElementException:
            airline_name.append('-')
        
        
    s = driver.find_elements_by_xpath('//div[@class="i-b col-4 no-wrap text-right dtime col-3"]/p')  
    for i in s:
        try:
            source.append(i.text)
        except NoSuchElementException:
            source.append('-')
        
        
    d = driver.find_elements_by_xpath("//div[@class='i-b pdd-0 text-left atime col-5']/p[2]")  
    for i in d:
        try:
            destination.append(i.text)
        except NoSuchElementException:
            destination.append('-')
        
        
    de = driver.find_elements_by_xpath("//div[@class='i-b col-4 no-wrap text-right dtime col-3']/div")  
    for i in de:
        try:
            departure_time.append(i.text)
        except NoSuchElementException:
            departure_time.append('-')
        
        
    a = driver.find_elements_by_xpath("//div[@class='i-b pdd-0 text-left atime col-5']/p[1]") 
    for i in a:
        try:
            arrival_time.append(i.text)
        except NoSuchElementException:
            arrival_time.append('-')
        
        
    du = driver.find_elements_by_xpath('//div[@class="stop-cont pl-13"]/p')
    for i in du:
        try:
            duration.append(i.text)
        except NoSuchElementException:
            duration.append('-')
        
        
        
    ts = driver.find_elements_by_xpath('//span[@class="dotted-borderbtm"]')
    for i in ts:
        try:
              
            total_stops.append(i.text)
        except NoSuchElementException:
            total_stops.append('-')
        

    p = driver.find_elements_by_xpath('//div[@class="i-b tipsy fare-summary-tooltip fs-18"]')
    for i in p:
        try:
              
            price.append(i.text)
        except NoSuchElementException:
            price.append('-')
        
        if (counter>3000):
            break
        else:
            counter += 1
    time.sleep(2)
print("Done Scraping!!!")

Done Scraping!!!

In [15]:
airline_data=pd.DataFrame({"Airline":airline_name})
source_data=pd.DataFrame({"Source":source})
destination_data=pd.DataFrame({"Destination":destination})
departure_time_data=pd.DataFrame({"Dep_Time":departure_time})
arrival_time_data=pd.DataFrame({"Arrival_Time":arrival_time})
duration_data=pd.DataFrame({"Duration":duration})
total_stops_data=pd.DataFrame({"Total_Stops":total_stops})
price_data=pd.DataFrame({"price":price})

In [16]:
data3=pd.concat([airline_data,source_data,destination_data,departure_time_data,arrival_time_data,duration_data,total_stops_data
          ,price_data],axis=1)
data3

,Airline,Source,Destination,Dep_Time,Arrival_Time,Duration,Total_Stops,price
0,Go First\nG8-385/382,Bangalore,Goa,06:30,16:30,10h 00m,1 Stop,"4,337"
1,Go First\nG8-385/371,Bangalore,Goa,06:30,17:45,11h 15m,1 Stop,"4,337"
2,Go First\nG8-801/913,Bangalore,Goa,05:40,20:35,14h 55m,1 Stop,"4,337"
3,IndiGo\n6E-194,Bangalore,Goa,06:15,07:35,1h 20m,1 Stop,"4,338"
4,IndiGo\n6E-6345,Bangalore,Goa,12:45,14:05,1h 20m,1 Stop,"4,338"
...,...,...,...,...,...,...,...,...
3005,Air India\nAI-808/665/663,Bangalore,Goa,21:00,14:45\n+ 1 day,17h 45m,NaN,NaN
3006,Air India\nAI-808/678/663,Bangalore,Goa,21:00,14:45\n+ 1 day,17h 45m,NaN,NaN
3007,Air India\nAI-808/887/663,Bangalore,Goa,21:00,14:45\n+ 1 day,17h 45m,NaN,NaN
3008,Air India\nAI-505/624/685,Bangalore,Goa,10:25,06:25\n+ 1 day,20h 00m,NaN,NaN
3009,Air India\nAI-505/868/685,Bangalore,Goa,10:25,06:25\n+ 1 day,20h 00m,NaN,NaN

In [17]:
# enter keyword to search (URL)
keyword="https://flight.yatra.com/air-search-ui/dom2/trigger?ADT=1&CHD=0&INF=0&class=Economy&destination=CCU&destinationCountry=IN&flexi=0&flight_depart_date=27%2F01%2F2022&hb=0&noOfSegments=1&origin=PNQ&originCountry=IN&type=O&unique=549527141892&version=1.1&viewName=normal"
driver.get(keyword)
time.sleep(35)
time.sleep(4)
# checking current window title
print('Current page: ',driver.title)




# Activating webdriver
for _ in range(5000):
    driver.execute_script("window.scrollBy(0,7000)")
time.sleep(10)


airline_name=[]
date_of_journey=[]
source=[]
destination=[]
departure_time=[] 
arrival_time=[]
duration=[]
total_stops=[] 
price=[]

counter = 1
#data = []
while (counter <=1100):
    an=driver.find_elements_by_xpath('//div[@class="fs-13 airline-name no-pad col-8"]')  
    for i in an:
        try:
            airline_name.append(i.text)
        except NoSuchElementException:
            airline_name.append('-')
        
        
    s = driver.find_elements_by_xpath('//div[@class="i-b col-4 no-wrap text-right dtime col-3"]/p')  
    for i in s:
        try:
            source.append(i.text)
        except NoSuchElementException:
            source.append('-')
        
        
    d = driver.find_elements_by_xpath("//div[@class='i-b pdd-0 text-left atime col-5']/p[2]")  
    for i in d:
        try:
            destination.append(i.text)
        except NoSuchElementException:
            destination.append('-')
        
        
    de = driver.find_elements_by_xpath("//div[@class='i-b col-4 no-wrap text-right dtime col-3']/div")  
    for i in de:
        try:
            departure_time.append(i.text)
        except NoSuchElementException:
            departure_time.append('-')
        
        
    a = driver.find_elements_by_xpath("//div[@class='i-b pdd-0 text-left atime col-5']/p[1]") 
    for i in a:
        try:
            arrival_time.append(i.text)
        except NoSuchElementException:
            arrival_time.append('-')
        
        
    du = driver.find_elements_by_xpath('//div[@class="stop-cont pl-13"]/p')
    for i in du:
        try:
            duration.append(i.text)
        except NoSuchElementException:
            duration.append('-')
        
        
        
    ts = driver.find_elements_by_xpath('//span[@class="dotted-borderbtm"]')
    for i in ts:
        try:
              
            total_stops.append(i.text)
        except NoSuchElementException:
            total_stops.append('-')
        

    p = driver.find_elements_by_xpath('//div[@class="i-b tipsy fare-summary-tooltip fs-18"]')
    for i in p:
        try:
              
            price.append(i.text)
        except NoSuchElementException:
            price.append('-')
        
        if (counter>1100):
            break
        else:
            counter += 1
    time.sleep(2)
print("Done Scraping!!!")

Current page:  Yatra.com | Pune to Kolkata flights
Done Scraping!!!

In [18]:
airline_data=pd.DataFrame({"Airline":airline_name})
source_data=pd.DataFrame({"Source":source})
destination_data=pd.DataFrame({"Destination":destination})
departure_time_data=pd.DataFrame({"Dep_Time":departure_time})
arrival_time_data=pd.DataFrame({"Arrival_Time":arrival_time})
duration_data=pd.DataFrame({"Duration":duration})
total_stops_data=pd.DataFrame({"Total_Stops":total_stops})
price_data=pd.DataFrame({"price":price})

data4=pd.concat([airline_data,source_data,destination_data,departure_time_data,arrival_time_data,duration_data,total_stops_data
          ,price_data],axis=1)
data4

,Airline,Source,Destination,Dep_Time,Arrival_Time,Duration,Total_Stops,price
0,Go First\nG8-174/7103,Pune,Kolkata,12:30,19:50,7h 20m,1 Stop,"7,742"
1,Go First\nG8-501/791,Pune,Kolkata,12:05,20:45,8h 40m,1 Stop,"7,742"
2,Go First\nG8-284/790,Pune,Kolkata,22:50,08:00\n+ 1 day,9h 10m,1 Stop,"7,742"
3,Go First\nG8-2541/101,Pune,Kolkata,19:10,08:00\n+ 1 day,12h 50m,1 Stop,"7,742"
4,SpiceJet\nSG-532/401,Pune,Kolkata,15:30,08:30\n+ 1 day,17h 00m,1 Stop,"7,742"
...,...,...,...,...,...,...,...,...
1115,Air India\n9I-9890/532/401,Pune,Kolkata,15:25,09:00\n+ 1 day,17h 35m,3 Stop(s),NaN
1116,Air India\n9I-9890/862/401,Pune,Kolkata,15:25,09:00\n+ 1 day,17h 35m,3 Stop(s),NaN
1117,Air India\n9I-9890/532/764,Pune,Kolkata,15:25,19:10\n+ 1 day,27h 45m,3 Stop(s),NaN
1118,Air India\n9I-9890/862/764,Pune,Kolkata,15:25,19:10\n+ 1 day,27h 45m,3 Stop(s),NaN
1119,Air India\nAI-482/544/525,Pune,Kolkata,12:45,08:05\n+ 1 day,19h 20m,3 Stop(s),NaN

In [19]:
# enter keyword to search (URL)
#keyword='https://flight.yatra.com/air-search-ui/dom2/trigger?ADT=1&CHD=0&INF=0&class=Economy&destination=MAA&destinationCountry=IN&flexi=0&flight_depart_date=27%2F01%2F2022&hb=0&noOfSegments=1&origin=BOM&originCountry=IN&type=O&unique=1508984995386&version=1.1&viewName=normal'
driver.get(keyword)
time.sleep(35)
# checking current window title
print('Current page: ',driver.title)




# Activating webdriver
for _ in range(5000):
    driver.execute_script("window.scrollBy(0,7000)")
time.sleep(10)


airline_name=[]
date_of_journey=[]
source=[]
destination=[]
departure_time=[] 
arrival_time=[]
duration=[]
total_stops=[] 
price=[]

counter = 1
#data = []
while (counter <=1100):
    an=driver.find_elements_by_xpath('//div[@class="fs-13 airline-name no-pad col-8"]')  
    for i in an:
        try:
            airline_name.append(i.text)
        except NoSuchElementException:
            airline_name.append('-')
        
        
    s = driver.find_elements_by_xpath('//div[@class="i-b col-4 no-wrap text-right dtime col-3"]/p')  
    for i in s:
        try:
            source.append(i.text)
        except NoSuchElementException:
            source.append('-')
        
        
    d = driver.find_elements_by_xpath("//div[@class='i-b pdd-0 text-left atime col-5']/p[2]")  
    for i in d:
        try:
            destination.append(i.text)
        except NoSuchElementException:
            destination.append('-')
        
        
    de = driver.find_elements_by_xpath("//div[@class='i-b col-4 no-wrap text-right dtime col-3']/div")  
    for i in de:
        try:
            departure_time.append(i.text)
        except NoSuchElementException:
            departure_time.append('-')
        
        
    a = driver.find_elements_by_xpath("//div[@class='i-b pdd-0 text-left atime col-5']/p[1]") 
    for i in a:
        try:
            arrival_time.append(i.text)
        except NoSuchElementException:
            arrival_time.append('-')
        
        
    du = driver.find_elements_by_xpath('//div[@class="stop-cont pl-13"]/p')
    for i in du:
        try:
            duration.append(i.text)
        except NoSuchElementException:
            duration.append('-')
        
        
        
    ts = driver.find_elements_by_xpath('//span[@class="dotted-borderbtm"]')
    for i in ts:
        try:
              
            total_stops.append(i.text)
        except NoSuchElementException:
            total_stops.append('-')
        

    p = driver.find_elements_by_xpath('//div[@class="i-b tipsy fare-summary-tooltip fs-18"]')
    for i in p:
        try:
              
            price.append(i.text)
        except NoSuchElementException:
            price.append('-')
        
        if (counter>1100):
            break
        else:
            counter += 1
    time.sleep(2)
print("Done Scraping!!!")

Current page:  Challenge Validation
Done Scraping!!!

In [20]:
airline_data=pd.DataFrame({"Airline":airline_name})
source_data=pd.DataFrame({"Source":source})
destination_data=pd.DataFrame({"Destination":destination})
departure_time_data=pd.DataFrame({"Dep_Time":departure_time})
arrival_time_data=pd.DataFrame({"Arrival_Time":arrival_time})
duration_data=pd.DataFrame({"Duration":duration})
total_stops_data=pd.DataFrame({"Total_Stops":total_stops})
price_data=pd.DataFrame({"price":price})

data5=pd.concat([airline_data,source_data,destination_data,departure_time_data,arrival_time_data,duration_data,total_stops_data
          ,price_data],axis=1)
data5

,Airline,Source,Destination,Dep_Time,Arrival_Time,Duration,Total_Stops,price
0,Go First\nG8-174/7103,Pune,Kolkata,12:30,19:50,7h 20m,1 Stop,"7,742"
1,Go First\nG8-501/791,Pune,Kolkata,12:05,20:45,8h 40m,1 Stop,"7,742"
2,Go First\nG8-284/790,Pune,Kolkata,22:50,08:00\n+ 1 day,9h 10m,1 Stop,"7,742"
3,Go First\nG8-2541/101,Pune,Kolkata,19:10,08:00\n+ 1 day,12h 50m,1 Stop,"7,742"
4,SpiceJet\nSG-532/401,Pune,Kolkata,15:30,08:30\n+ 1 day,17h 00m,1 Stop,"7,742"
...,...,...,...,...,...,...,...,...
1095,Vistara\nUK-998/747,Pune,Kolkata,16:55,08:35\n+ 1 day,15h 40m,1 Stop,"10,209"
1096,Vistara\nUK-998/705,Pune,Kolkata,16:55,09:35\n+ 1 day,16h 40m,1 Stop,"10,209"
1097,Vistara\nUK-998/737,Pune,Kolkata,16:55,18:05\n+ 1 day,25h 10m,1 Stop,"10,209"
1098,Vistara\nUK-998/707,Pune,Kolkata,16:55,19:35\n+ 1 day,26h 40m,1 Stop,"10,388"
1099,Air India\nAI-482/762,Pune,Kolkata,12:45,00:05\n+ 1 day,11h 20m,2 Stop(s),"11,838"

In [49]:
cars2=data1.append(data2)
len(cars2)

2030

In [50]:
flight=cars2.append(data3[:2500]).append(data4[:1100]).append(data5[:1100])

In [51]:
len(flight)

6730

In [53]:
flight.to_csv('Web_Scraped_flight.csv')

In [54]:
df=pd.read_csv("Web_Scraped_flight.csv")
df